= Chronicle Release Notes

Chronicle Release Notes is a library and CLI utility designed to automate the generation of release notes for GitHub repositories.

== Requirements

Before using the Chronicle Release Notes, make sure you have the following installed on your system:

- link:https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html[Java 8]
- link:https://maven.apache.org/[Maven]/link:https://gradle.org/[Gradle]

== Installation

Maven:

```xml
<dependencies>
    ...
    <dependency>
        <groupId>net.openhft</groupId>
        <artifactId>chronicle-release-notes-connector-all</artifactId>
        <version>${chronicle-release-notes.version}</version>
    </dependency>
    ...
</dependencies>
```

Gradle:

```groovy
dependencies {
    ...
    implementation "net.openhft:chronicle-release-notes-connector-all:${chronicle-release-notes.version}"
    ...
}
```

== Connecting to GitHub

Before a release can be created, we must first gain access to GitHub's API. That can be done using the following code:

```java
final ConnectorProvider<ReleaseConnector> releaseConnectorProvider = ConnectorProviderFactory.getInstance()
    .getReleaseConnectorProvider(ConnectorProviderKeys.GITHUB)
    .orElseThrow(() -> new RuntimeException("Failed to find GitHub release provider"));

final ReleaseConnector releaseConnector = releaseConnectorProvider.connect("YOUR_PERSONAL_ACCESS_TOKEN")
    .orElseThrow(() -> new RuntimeException("Failed to connect to GitHub"));
```

== Creating a release

With Chronicle Release Notes, users are able to create releases from 2 sources - branches and milestones:

=== Creating a release from a branch source

```java
final ReleaseResult releaseResult = releaseConnector.createReleaseFromBranch("owner/repository", "1.0.0", "master");

releaseResult.throwIfFail();
```

==== Overriding existing releases
```java
final BranchReleaseOptions releaseOptions = new BranchReleaseOptions.Builder()
    .overrideRelease(true)
    .build();

final ReleaseResult releaseResult = releaseConnector.createReleaseFromBranch("owner/repository", "1.0.0", "master", releaseOptions);

releaseResult.throwIfFail();
```

==== Ignoring issues with specific labels
```java
final BranchReleaseOptions releaseOptions = new BranchReleaseOptions.Builder()
    .ignoreLabels("wontfix")
    .build();

final ReleaseResult releaseResult = releaseConnector.createReleaseFromBranch("owner/repository", "1.0.0", "master", releaseOptions);

releaseResult.throwIfFail();
```

=== Creating a release from a milestone source

```java
final ReleaseResult = releaseConnector.createReleaseFromMilestone("owner/respository", "1.0.0", "milestone1");

releaseResult.throwIfFail();
```

==== Overriding existing releases
```java
final MilestoneReleaseOptions releaseOptions = new MilestoneReleaseOptions.Builder()
    .overrideRelease(true)
    .build();

final ReleaseResult releaseResult = releaseConnector.createReleaseFromMilestone("owner/repository", "1.0.0", "milestone1", releaseOptions);

releaseResult.throwIfFail();
```

==== Ignoring issues with specific labels
```java
final MilestoneReleaseOptions releaseOptions = new MilestoneReleaseOptions.Builder()
    .ignoreLabels("wontfix")
    .build();

final ReleaseResult releaseResult = releaseConnector.createReleaseFromMilestone("owner/repository", "1.0.0", "milestone1", releaseOptions);

releaseResult.throwIfFail();
```
